theme: jekyll-theme-architect
title: Welcome to Applied genomics (BL4300-5300)
description: This is the class page for Applied Genomics at MTU
url: https://stechtmann.github.io/BL4300-5300/
baseurl: /Page2
